like_publication:
  path: /like/{id}
  defaults: { _controller: AppBundle:Like:like, id: null }

dislike_publication:
  path: /dislike/{id}
  defaults: { _controller: AppBundle:Like:dislike, id: null }

user_likes:
  path: /likes/{nick}
  defaults: { _controller: AppBundle:Like:likesList, nick: null }