skill_index:
    path:     /
    defaults: { _controller: "KhairiSNEspritBundle:Skill:index" }
    methods:  GET

skill_show:
    path:     /{id}/show
    defaults: { _controller: "KhairiSNEspritBundle:Skill:show" }
    methods:  GET

skill_new:
    path:     /new
    defaults: { _controller: "KhairiSNEspritBundle:Skill:new" }
    methods:  [GET, POST]

skill_edit:
    path:     /{id}/edit
    defaults: { _controller: "KhairiSNEspritBundle:Skill:edit" }
    methods:  [GET, POST]

skill_delete:
    path:     /{id}/delete
    defaults: { _controller: "KhairiSNEspritBundle:Skill:delete" }
    methods:  DELETE

skill_redirect:
    path:     /types
    defaults: { _controller: "KhairiSNEspritBundle:Skill:redirect" }   