services:
  tag.form.type.tags:
        class: Khairi\SNEspritBundle\Form\Type\TagsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
#    khairi_sn_esprit.example:
#        class: Khairi\SNEspritBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    